version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - ./volumes/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./volumes/pgdata:/data/postgres
      - ./volumes/create_role.sql:/create_role.sql
      - ./volumes/postgresql.conf:/data/postgres/postgresql.conf
      - ../db:/db
    ports:
      - "5433:5432"
    restart: unless-stopped