[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4.3"
lazy_static  = "1.4.0"
regex = "1.5"
tokio = { version = "1.12", features = ["full"] }
futures = "0.3"
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "mysql" ] }
rand = "0.8"
flate2 = "1.0"
md5 = "0.7.0"
log = "0.4"
flexi_logger = "0.19"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
eframe = { version = "0.15", default-features = false, features = ["egui_glow", "default_fonts"] }

accessor = { path = "../lib/accessor" }
metrics = { path = "../lib/metrics" }
packets = { path = "../lib/packets" }
sql = { path = "../lib/sql" }

[[bin]]
name = "packets"
path = "../tools/packets/main.rs"
[[bin]]
name = "maps"
path = "../tools/map-cache/main.rs"

[features]
visual_debugger = []
